AWSTemplateFormatVersion: 2010-09-09

Description: Defines user, policy, and role for a Github Actions user

Resources:
  GithubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Join ["", ["arn:aws:iam::", !Ref AWS::AccountId, ":root"]]
            Action:
              - sts:AssumeRole
              - sts:TagSession
      Policies:
        - PolicyName: GithubActionsS3Permissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:ListChangeSets
                  - cloudformation:ListExports
                  - cloudformation:ListImports
                  - cloudformation:ListStacks
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:TagResource
                  - cloudformation:UpdateStack
                  - cloudformation:ValidateTemplate
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                Resource: "*"
              - Effect: "Allow"
                Action:
                  # - ec2:DescribeVpcs
                  # - ec2:CreateVpc
                  # - ec2:DeleteVpc
                  # - ec2:CreateSubnet
                  # - ec2:DescribeSubnets
                  # - ec2:DeleteSubnet
                  # - ec2:DescribeAvailabilityZones
                  # - ec2:CreateRouteTable
                  # - ec2:DescribeRouteTables
                  # - ec2:DeleteRouteTable
                  # - ec2:DescribeRoutes
                  # - ec2:CreateRoute
                  # - ec2:DeleteRoute
                  # - ec2:DescribeInternetGateways
                  # - ec2:CreatenternetGateway
                  # - ec2:DeleteInternetGateway
                  # - ec2:AttachInternetGateway
                  # - ec2:AssociateRouteTable
                  # - ec2:ModifyVpcAttribute
                  # - ec2:CreateTags
                  # - ec2:DeleteTags
                  # - ec2:AssociateVpcCidrBlockRequest
                  - ec2:*
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - iam:GetRole
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRolePolicy
                  - iam:CreateRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:PutRolePolicy
                  - iam:PassRole
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - lambda:GetFunction
                  - lambda:CreateFunction
                  - lambda:DeleteFunction
                  - lambda:InvokeFunction
                Resource: "*"
  GithubActionsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: GithubActionsPolicy
      Users:
        - !Ref GithubActionsUser
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
              - sts:TagSession
            Resource: !GetAtt GithubActionsRole.Arn
  GithubActionsUser:
    Type: AWS::IAM::User
    Properties:
      UserName: GithubActions
