AWSTemplateFormatVersion: "2010-09-09"
Description:
  Cloudformation for a 3-tier (+reserved tier) VPC across three AZs.
Metadata:
  LICENSE: Apache License Version 2.0
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.16.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: vpc1
  IPv6CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      VpcId: !Ref VPC
      AmazonProvidedIpv6CidrBlock: true
  SubnetReservedA:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.16.0.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock:
        !Sub:
          - "${VpcPart}${SubnetPart}"
          - SubnetPart: "00::/64"
            VpcPart:
              !Select [0,!Split ["00::/56", !Select [0, !GetAtt VPC.Ipv6CidrBlocks]],]
      Tags:
        - Key: Name
          Value: subnet-reserved-A
  SubnetReservedB:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.16.64.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock:
        !Sub:
          - "${VpcPart}${SubnetPart}"
          - SubnetPart: "04::/64"
            VpcPart:
              !Select [0,!Split ["00::/56", !Select [0, !GetAtt VPC.Ipv6CidrBlocks]],]
      Tags:
        - Key: Name
          Value: subnet-reserved-B
  SubnetReservedC:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs ""]
      CidrBlock: 10.16.128.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock:
        !Sub:
          - "${VpcPart}${SubnetPart}"
          - SubnetPart: "08::/64"
            VpcPart:
              !Select [0,!Split ["00::/56", !Select [0, !GetAtt VPC.Ipv6CidrBlocks]],]
      Tags:
        - Key: Name
          Value: subnet-reserved-C
  SubnetDBA:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.16.16.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock:
        !Sub:
          - "${VpcPart}${SubnetPart}"
          - SubnetPart: "01::/64"
            VpcPart:
              !Select [0,!Split ["00::/56", !Select [0, !GetAtt VPC.Ipv6CidrBlocks]],]
      Tags:
        - Key: Name
          Value: subnet-db-A
  SubnetDBB:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.16.80.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock:
        !Sub:
          - "${VpcPart}${SubnetPart}"
          - SubnetPart: "05::/64"
            VpcPart:
              !Select [0,!Split ["00::/56", !Select [0, !GetAtt VPC.Ipv6CidrBlocks]],]
      Tags:
        - Key: Name
          Value: subnet-db-B
  SubnetDBC:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs ""]
      CidrBlock: 10.16.144.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock:
        !Sub:
          - "${VpcPart}${SubnetPart}"
          - SubnetPart: "09::/64"
            VpcPart:
              !Select [0,!Split ["00::/56", !Select [0, !GetAtt VPC.Ipv6CidrBlocks]],]
      Tags:
        - Key: Name
          Value: subnet-db-C
  SubnetAPPA:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.16.32.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock:
        !Sub:
          - "${VpcPart}${SubnetPart}"
          - SubnetPart: "02::/64"
            VpcPart:
              !Select [0,!Split ["00::/56", !Select [0, !GetAtt VPC.Ipv6CidrBlocks]],]
      Tags:
        - Key: Name
          Value: subnet-app-A
  SubnetAPPB:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.16.96.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock:
        !Sub:
          - "${VpcPart}${SubnetPart}"
          - SubnetPart: "06::/64"
            VpcPart:
              !Select [0,!Split ["00::/56", !Select [0, !GetAtt VPC.Ipv6CidrBlocks]],]
      Tags:
        - Key: Name
          Value: subnet-app-B
  SubnetAPPC:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs ""]
      CidrBlock: 10.16.160.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock:
        !Sub:
          - "${VpcPart}${SubnetPart}"
          - SubnetPart: "0A::/64"
            VpcPart:
              !Select [0,!Split ["00::/56", !Select [0, !GetAtt VPC.Ipv6CidrBlocks]],]
      Tags:
        - Key: Name
          Value: subnet-app-C
  SubnetWEBA:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.16.48.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock:
        !Sub:
          - "${VpcPart}${SubnetPart}"
          - SubnetPart: "03::/64"
            VpcPart:
              !Select [0,!Split ["00::/56", !Select [0, !GetAtt VPC.Ipv6CidrBlocks]],]
      Tags:
        - Key: Name
          Value: subnet-web-A
  SubnetWEBB:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.16.112.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock:
        !Sub:
          - "${VpcPart}${SubnetPart}"
          - SubnetPart: "07::/64"
            VpcPart:
              !Select [0,!Split ["00::/56", !Select [0, !GetAtt VPC.Ipv6CidrBlocks]],]
      Tags:
        - Key: Name
          Value: subnet-web-B
  SubnetWEBC:
    Type: AWS::EC2::Subnet
    DependsOn: IPv6CidrBlock
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs ""]
      CidrBlock: 10.16.176.0/20
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock:
        !Sub:
          - "${VpcPart}${SubnetPart}"
          - SubnetPart: "0B::/64"
            VpcPart:
              !Select [0,!Split ["00::/56", !Select [0, !GetAtt VPC.Ipv6CidrBlocks]],]
      Tags:
        - Key: Name
          Value: subnet-web-C
