name: Deploy NAT Gateways

on:
  # Run this workflow manually from the Actions tab
  workflow_dispatch:
    # inputs:
    #   region:
    #     description: "AWS Region"
    #     required: true
    #     default: "us-east-1"
      # bucketName:
      #   description: "S3 Bucket Name"
      #   required: true

jobs:
  cfn-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: GithubActionSession
      - name: Deploy NAT Gateway stack
        id: nat_gateway
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: nat_gateway
          template: cloudformation-templates/nat_gateways.yml
          # parameter-overrides: >-
          #   BucketName=${{ github.event.inputs.bucketName }}
